package com.example.c301_w16_g5.c301_w16_g5;

import android.net.Uri;
import android.os.Parcel;
import android.os.Parcelable;

import java.net.URI;
import java.util.ArrayList;
import java.util.List;

import io.searchbox.annotations.JestId;

/**
 * A <code>Chicken</code> is the item of trade around which the application is
 * based.  Users borrow chickens from other users who own them, determined by
 * a bidding system.  Chickens are searchable in a database.
 *
 * @author  Robin
 * @version 1.4, 03/02/2016
 * @see     User
 * @see     Bid
 * @see     Photograph
 * @see     ElasticSearchBackend
 * @see     ChickenController
 * @see     ChickenActivity
 * @see     AddChickenActivity
 * @see     EditChickenActivity
 * @see     OwnerChickenProfileActivity
 * @see     BorrowerChickenProfileActivity
 */
public class Chicken extends GenericModel<GenericView> implements Parcelable {
    public enum ChickenStatus {
        AVAILABLE,
        BORROWED,
        BIDDED,
        NOT_AVAILABLE
    }
    @JestId
    protected String id;

    private String name;
    private String description;
    private ChickenStatus chickenStatus;
    private String owner_username;
    private String borrower_username;
    private ArrayList<Bid> bids;
    private Uri picture;
    private Photograph photo;

    protected Chicken() {
        bids = new ArrayList<Bid>();
    }

    public Chicken(String name, String description, String owner_username) {
        this.name = name;
        this.description = description;
        this.chickenStatus = ChickenStatus.AVAILABLE;
        this.owner_username = owner_username;
        this.bids = new ArrayList<Bid>();
    }

    public void update(String name, String description, ChickenStatus chickenStatus) {
        this.name = name;
        this.description = description;
        this.chickenStatus = chickenStatus;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ChickenStatus getChickenStatus() {
        return chickenStatus;
    }

    public void setChickenStatus(ChickenStatus chickenStatus) {
        this.chickenStatus = chickenStatus;
    }

    public String getOwnerUsername() {
        return owner_username;
    }

    public void setOwnerUsername(String owner_username) {
        this.owner_username = owner_username;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ArrayList<Bid> getBids() {
        return bids;
    }

    public void addBid(Bid bid) {
        bids.add(bid);
    }

    public void deleteBidForId(String id) {
        ArrayList<Bid> bids = getBids();
        for (Bid b : bids) {
            if (b.getId().equals(id)) {
                bids.remove(b);
                break;
            }
        }
    }

    public String getBorrowerUsername() {
        return borrower_username;
    }

    public void setBorrowerUsername(String borrower_username) {
        this.borrower_username = borrower_username;
    }

    public Photograph getPhoto() {
        return photo;
    }

    public void setPhoto(Photograph photo) {
        this.photo = photo;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Uri getPicture() {
        return picture;
    }

    public void setPicture(Uri picture) {
        this.picture = picture;
    }

    // Generated by Android Parcelable Generator
    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.id);
        dest.writeString(this.name);
        dest.writeString(this.description);
        dest.writeInt(this.chickenStatus == null ? -1 : this.chickenStatus.ordinal());
        dest.writeString(this.owner_username);
        dest.writeString(this.borrower_username);
        dest.writeList(this.bids);
        dest.writeParcelable(this.photo, flags);
    }

    protected Chicken(Parcel in) {
        this.id = in.readString();
        this.name = in.readString();
        this.description = in.readString();
        int tmpChickenStatus = in.readInt();
        this.chickenStatus = tmpChickenStatus == -1 ? null : ChickenStatus.values()[tmpChickenStatus];
        this.owner_username = in.readString();
        this.borrower_username = in.readString();
        this.bids = new ArrayList<Bid>();
        in.readList(this.bids, List.class.getClassLoader());
        this.photo = in.readParcelable(Photograph.class.getClassLoader());
    }

    public static final Creator<Chicken> CREATOR = new Creator<Chicken>() {
        public Chicken createFromParcel(Parcel source) {
            return new Chicken(source);
        }

        public Chicken[] newArray(int size) {
            return new Chicken[size];
        }
    };
}
